"""
Author: Stefan Peidli
Date: 16.03.2023
Run: snakemake
"""

from pathlib import Path
configfile: "../../config.yaml"

### PATHS ###
DATADIR = Path(config['DOWNDIR'])  # place to store data
TEMPDIR = Path(config['TEMPDIR'])  # place to store temporary files (huge files)

### RULES ###
rule McFalineTrapnell2023_download:
    output:
        TEMPDIR / 'McFalineTrapnell2023/downloaded.flag'
    resources:
        partititon='short',
        time='04:00:00',
        mem_mb=64000,
        disk_mb=64000
    shell:
        """
        cd {TEMPDIR}/McFalineTrapnell2023
        wget -O GSE225775_RAW.tar 'http://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE225775&format=file'
        tar -xvf GSE225775_RAW.tar
        rm GSE225775_RAW.tar
        touch {output}
        """

rule McFalineTrapnell2023:
    input: TEMPDIR / 'McFalineTrapnell2023/downloaded.flag'
    output:
    resources:
        partititon='short',
        time='04:00:00',
        mem_mb=128000,
        disk_mb=128000
    script:
        'McFalineTrapnell2023.py'