"""
Author: Stefan Peidli
Aim: Snakemake workflow for downloading and processing scperturb data.
Date: 07.01.2023
Run: snakemake
Run (dev): snakemake --profile=cubi-v1 --jobs 100 -k --use-conda --restart-times 0 --rerun-triggers mtime
Create DAG: snakemake --forceall --dag | dot -Tpdf > snake_dag.pdf
Create Rulegraph: snakemake --forceall --rulegraph | dot -Tpdf > snake_rulegraph.pdf
"""

